config/routes.rb
GameOfTheCalf::Application.routes.draw do

  devise_for :markets
  resources :markets
  as :market do
    post 'markets/:id/selection' => 'markets#selection'
    post 'markets/:id/vote' => 'markets#vote'
    get 'markets/:id/bids' => 'markets#bids', :as => 'bids_market'
  end

  devise_for :game_configs
  resources :game_configs

  devise_for :levels
  resources :levels

  devise_for :games
  resources :games
  as :game do
    post 'games/:id/nextlevel' => 'games#nextlevel', :as => 'next_level'
  end


  root :to => 'game#welcome'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :groups


  #devise_for :users
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :users

  devise_for :groups
  as :group do
    post 'groups/:id/generateusers' => 'groups#generateusers', :as => 'generate_users'
    get 'groups/:id/nextlevel' => 'groups#nextlevel', :as => 'next_group_level'
    get 'groups/:id/games/:gid/forcenextlevel' => 'groups#forcenextlevel', :as => 'group_force_next_level'
    get 'groups/:id/market/open' => 'groups#open_market', :as => 'group_open_market'
    get 'groups/:id/market/close' => 'groups#close_market', :as => 'group_close_market'
    get 'groups/:id/market/cancel' => 'groups#cancel_market', :as => 'group_cancel_market'
    get 'groups/:id/market/bids' => 'groups#bids_market', :as => 'group_bids_market'
  end

  match 'users/create' => 'users#create', :via => :post, :as => :create_user

  match 'game/locale/:id' => 'game#locale'

  match 'credits' => 'game#credits'

  match 'tutorial' => 'game#tutorial'

  match 'game/admin' => 'game#admin', :via => :get


end

app/models/game_config.rb
class GameConfig < ActiveRecord::Base
  attr_accessible :mortality, :nbtrait, :mean_weight, :sex_effect, :heritability, :covar_envPermanent, :weight_month, :covar_weight, :default

  has_one :group
end

app/controllers/game_configs_controller.rb
class GameConfigsController < InheritedResources::Base

  before_filter :authenticate_user!

end

app/helpers/game_configs_helper.rb
module GameConfigsHelper
end

app/views/game_configs/_form.html.erb
<%= simple_form_for(@game_config) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nbtrait %>
    <%= f.input :mortality %>
    <%= f.label :sex_effect %>
    <%= f.text_field :sex_effect %>

<p>
  <b>Heritability:</b>
  <%= f.hidden_field :heritability, { :class => 'matrix', :'data-field' => 'heritability' } %>
  <table class="table">
  <thead><tr><th>W4Md</th><th>W7Md</th><th>W4Mm</th><th>W7Mm</th></tr></thead>
  <tbody id="heritability"></tbody>
  </table>
</p>

<p>
  <b>Covariance weight:</b>
  <%= f.hidden_field :covar_weight, { :class => 'matrix', :'data-field' => 'covar_weight' } %>
  <table class="table">
  <thead><tr><th>W4Md</th><th>W7Md</th><th>W4Mm</th><th>W7Mm</th></tr></thead>
  <tbody id="covar_weight"></tbody>
  </table>
</p>

<p>
  <b>Mean weight:</b>
  <%= f.hidden_field :mean_weight, { :class => 'matrix', :'data-field' => 'mean_weight' } %>
  <table class="table">
  <thead><tr><th>W4M</th><th>W7M</th></tr></thead>
  <tbody id="mean_weight"></tbody>
  </table>
</p>

<p>
  <b>Covariance env permanent:</b>
  <%= f.hidden_field :covar_envPermanent, { :class => 'matrix', :'data-field' => 'covar_envPermanent' } %>
  <table class="table">
  <thead><tr><th>W4M</th><th>W7M</th></tr></thead>
  <tbody id="covar_envPermanent"></tbody>
  </table>
</p>


<script>
$(function() {

$.each($(".matrix"),function() {
   values = $(this).val();
   id = $(this).attr('data-field');
   lines = values.split('|');
   matrix = '';
   for(var i=0;i<lines.length;i++) {
    matrix += '<tr>'; 
    cells = lines[i].split(',');
    for(var j=0;j<cells.length;j++) {
      matrix+='<td contenteditable="true">'+cells[j]+'</td>';
    }
    matrix += '</tr>';
   }
   $("#"+id).html(matrix);

});


$(document).on('blur',"tbody td", function(e) {
    var attr = $(e.currentTarget).parent().parent().attr('id');
    var rows = $("#"+attr+" > tr");
    var newvalues = "";
    var firstcell = true;
    var firstcol = true;
    $.each(rows, function() {
    	var cells = $(this).children();
    	if(! firstcol) { newvalues += "|";}
    	$.each(cells, function() {
    		if(! firstcell) { newvalues += ",";}
    		newvalues += $(this).text();
    		firstcell = false;
    	});
 		firstcol = false;
 		firstcell= true;
    });
    $("#game_config_"+attr).val(newvalues);
    console.log("update with "+newvalues);
	
});


});

</script>

  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_configs/edit.html.erb
<h1>Editing game_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_config %> |
<%= link_to 'Back', game_configs_path %>

app/views/game_configs/index.html.erb
<h1>Listing game_configs</h1>

<table>
  <tr>
    <th>Default</th>
    <th>Nbtrait</th>
    <th>Mortality</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @game_configs.each do |game_config| %>
  <tr>
    <td><%= game_config.default %></td>
    <td><%= game_config.nbtrait %></td>
    <td><%= game_config.mortality %></td>
    <td><%= link_to 'Show', game_config %></td>
    <td><%= link_to 'Edit', edit_game_config_path(game_config) %></td>
    <td><%= link_to 'Destroy', game_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game config', new_game_config_path %>

app/views/game_configs/new.html.erb
<h1>New game_config</h1>

<%= render 'form' %>

<%= link_to 'Back', game_configs_path %>

app/views/game_configs/show.html.erb
<%= link_to 'Edit', edit_game_config_path(@game_config) %> |
<%= link_to 'Back', game_configs_path %>


<p id="notice"><%= notice %></p>

<p>
  <b>Nbtrait:</b>
  <%= @game_config.nbtrait %>
</p>

<p>
  <b>Mortality:</b>
  <%= @game_config.mortality %>
</p>

<p>
  <b>Sex effect:</b>
  <%= @game_config.sex_effect %>
</p>

<p>
  <b>Heritability:</b>
  <input type="hidden" value="<%= @game_config.heritability %>" class="matrix" data-field="heritability"/>
  <table class="table">
  <thead><tr><th>W4Md</th><th>W7Md</th><th>W4Mm</th><th>W7Mm</th></tr></thead>
  <tbody id="heritability"></tbody>
  </table>
</p>

<p>
  <b>Covariance weight:</b>
  <input type="hidden" value="<%= @game_config.covar_weight %>" class="matrix" data-field="covar_weight"/>
  <table class="table">
  <thead><tr><th>W4Md</th><th>W7Md</th><th>W4Mm</th><th>W7Mm</th></tr></thead>
  <tbody id="covar_weight"></tbody>
  </table>
</p>

<p>
  <b>Mean weight:</b>
  <input type="hidden" value="<%= @game_config.mean_weight %>" class="matrix" data-field="mean_weight"/>
  <table class="table">
  <thead><tr><th>W4M</th><th>W7M</th></tr></thead>
  <tbody id="mean_weight"></tbody>
  </table>
</p>

<p>
  <b>Covariance env permanent:</b>
  <input type="hidden" value="<%= @game_config.covar_envPermanent %>" class="matrix" data-field="covar_envPermanent"/>
  <table class="table">
  <thead><tr><th>W4M</th><th>W7M</th></tr></thead>
  <tbody id="covar_envPermanent"></tbody>
  </table>
</p>


<script>
$(function() {

$.each($(".matrix"),function() {
   values = $(this).val();
   id = $(this).attr('data-field');
   lines = values.split('|');
   matrix = '';
   for(var i=0;i<lines.length;i++) {
    matrix += '<tr>'; 
    cells = lines[i].split(',');
    for(var j=0;j<cells.length;j++) {
      matrix+='<td>'+cells[j]+'</td>';
    }
    matrix += '</tr>';
   }
   $("#"+id).html(matrix);

});



});

</script>