config/routes.rb
GameOfTheCalf::Application.routes.draw do

  devise_for :markets
  resources :markets
  as :market do
    post 'markets/:id/selection' => 'markets#selection'
    post 'markets/:id/vote' => 'markets#vote'
    get 'markets/:id/bids' => 'markets#bids', :as => 'bids_market'
  end

  devise_for :game_configs
  resources :game_configs

  devise_for :levels
  resources :levels

  devise_for :games
  resources :games
  as :game do
    post 'games/:id/nextlevel' => 'games#nextlevel', :as => 'next_level'
  end


  root :to => 'game#welcome'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :groups


  #devise_for :users
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :users

  devise_for :groups
  as :group do
    post 'groups/:id/generateusers' => 'groups#generateusers', :as => 'generate_users'
    get 'groups/:id/nextlevel' => 'groups#nextlevel', :as => 'next_group_level'
    get 'groups/:id/games/:gid/forcenextlevel' => 'groups#forcenextlevel', :as => 'group_force_next_level'
    get 'groups/:id/market/open' => 'groups#open_market', :as => 'group_open_market'
    get 'groups/:id/market/close' => 'groups#close_market', :as => 'group_close_market'
    get 'groups/:id/market/cancel' => 'groups#cancel_market', :as => 'group_cancel_market'
    get 'groups/:id/market/bids' => 'groups#bids_market', :as => 'group_bids_market'
  end

  match 'users/create' => 'users#create', :via => :post, :as => :create_user

  match 'game/locale/:id' => 'game#locale'

  match 'credits' => 'game#credits'

  match 'tutorial' => 'game#tutorial'

  match 'game/admin' => 'game#admin', :via => :get


end

app/models/group.rb
require 'tempfile'
require 'fileutils'

# Group is used to group a set of Users.
# User is in one group only.
# Group can be seen as a classroom owner by a professor.
class Group < ActiveRecord::Base
  attr_accessible :description, :name, :email, :levels
  attr_accessible :bulls, :cows, :config_id, :market

  scope :recent, order("created_at desc")

  has_many :users, :dependent => :nullify
  has_many :games, :dependent => :nullify

  def mate()
    # Do mating for a group of user   
    games = Game.where(:group_id => self[:id])
    matingplans = {}
    gen = nil
    games.each do |game|
      gen = game[:level]
      level = Level.where(:game_id => game[:id], :level => game[:level]).first
      matingplans[game[:cattle]] = JSON.parse(level[:matingplan])
      if game[:level]< Settings.max_levels
        # Go to next level
        game[:level] += 1
        game[:status] = Level::STATUS_NEW

        level = Level.new(:game_id => game.id, :status => Level::STATUS_NEW, :level => game[:level])
        level.save!
      else
        game[:status] = Level::STATUS_COMPLETED
      end
      game.save
    end
    do_mating = Game.writeMatingPlan("group"+self[:id].to_s, gen+1, matingplans)
    if do_mating
      Game.mate("group"+self[:id].to_s, gen+1)
    end
    # Set statistics for each game
    games.each do |game|
      game.load_statistics()
      game.save 
    end
  end

  def close_market()
    # Get one game from the current group
    one_game = Game.where(:group_id => self[:id]).first()
    one_user = User.where(:id => one_game[:user_id]).first()
    cattle_path = one_game.get_cattle_path(one_user)
    cattle_file = 'bullMate_perfVG_Flock-1_generation-'+one_game.level.to_s+'.txt'
    # Select market_max_final best animal bids
    bids = Bid.select("sum(bid) as bids, market_id").where(:group_id => self[:id]).group("market_id").order("bids DESC").first(Settings.market_max_final)
    allowed_users = {}
    # Only users that made proposals can benefit from IA selection
    markets = Market.where(:group_id => self[:id])
    markets.each do |market|
      if ! allowed_users.has_key?(market[:owner])
          allowed_users[market[:owner].to_s] = true
      end    
    end

    tmpfile = Tempfile.new('bullmate')
    last_userid = nil
    last_animal_id = nil
    CSV.foreach(cattle_path + '/' + cattle_file, { col_sep: "\t" }) do |row|
       userid = row[0]
       animal_id = row[1]
       # init userid
       if last_userid == nil
         last_userid = userid
       end
       if last_animal_id == nil
         last_animal_id = animal_id
       end
       # if we switch to a new user, add IA animals, only if not from current
       # user
       if userid != last_userid
         if allowed_users.has_key?(last_userid)
           count = last_animal_id.to_i+1
           bids.each do |bid|
             market = Market.find(bid[:market_id])
             values = JSON.parse(market[:values])
             values[0] = last_userid
             values[1] = count.to_s
             count += 1
             values << "1"
             values << market[:owner].to_s+"-"+market[:animal].to_s
             tmpfile.write values.join("\t")+"\n" 
           end
         end
         last_userid = userid
       end
       last_animal_id = animal_id
       tmpfile.write row.join("\t")+"\n"
    end

    # Last user
    if allowed_users.has_key?(last_userid)
       count = last_animal_id.to_i+1
       bids.each do |bid|
         market = Market.find(bid[:market_id])
         values = JSON.parse(market[:values])
         values[0] = last_userid
         values[1] = count.to_s
         count += 1
         values << "1"
         values << market[:owner].to_s+"-"+market[:animal].to_s
         tmpfile.write values.join("\t")+"\n"
       end
    end
    tmp_file_path = tmpfile.path
    tmpfile.close()
    tmp_file = File.open(tmp_file_path,"r")

    new_cattle_file = File.open(cattle_path + '/' + cattle_file,"w")
    new_cattle_file.write(tmp_file.read)
    new_cattle_file.close()
    tmp_file.close()
    tmpfile.close()
  end


end

app/controllers/groups_controller.rb
# Base controller for managing groups
class GroupsController < ApplicationController

  before_filter :authenticate_user!

  # GET /groups
  # GET /groups.json
  def index
    if params[:group] && params[:group][:search]
      @groups = Group.where(:email => current_user.email).paginate(:page => params[:page], :per_page => 20, :conditions => ['lower(name) LIKE ? ', "%#{params[:group][:search]}%"])
    else
      @groups = Group.where(:email => current_user.email).paginate(:page => params[:page], :per_page => 20)
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups.to_json() }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    authorize! :read, @group

    users_in_group = User.where(:group_id => @group[:id])

    #@group.users = []
    #users_in_group.each do |user|
    #    @group.users << { :id => user[:id], :email => user[:email] }
    #end

    @users = User.where(:group_id => @group[:id])

    @games = Game.where(:group_id => @group[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
    @group.email =  current_user.email
    @professors = nil
    if User.admin?(current_user)
      @professors = User.where(:usertype => User::PROFESSOR)
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /group/1/edit
  def edit
    @group = Group.find(params[:id])
    
    authorize! :update, @group
    @professors = nil
    if User.admin?(current_user)
      @professors = User.where(:usertype => User::PROFESSOR)
    end

  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    authorize! :create, @group

    @group.email = current_user.email unless User.admin?(current_user)

    config = GameConfig.where(:default => true).first.dup
    config.save
    @group[:config_id] = config[:id]

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    authorize! :update, @group
    params[:group][:email] = current_user.email unless User.admin?(current_user)
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    authorize! :destroy, @group

    users_in_group = User.where(:group_id => @group[:id], :fake => 0)
    users_in_group.each do |user|
        user[:group_id] = nil
        user.save
    end
    # Delete all users in group
    users_in_group = User.where(:group_id => @group[:id], :fake => 1)
    users_in_group.each do |user|
        # Delete user games
        user_games = Game.where(:user_id => user[:id])
        user_games.each do |game|
            # Delete game levels
            Level.delete_all(:game_id => game[:id])
            #game_levels.each do |level|
            #    level.destroy
            #end
            game.destroy
        end
        user.destroy
    end

    if ! @group[:config_id].nil?
        config = GameConfig.find(@group[:config_id])
        config.destroy
    end

    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def forcenextlevel
    @group = Group.find(params[:id])
    authorize! :create, @group
    @game = Game.find(params[:gid])

    matingPlan = @game.generateFakeMatingPlan()

    level = Level.where(:game_id => @game.id, :level => @game[:level]).first
    level[:matingplan] = JSON.generate(matingPlan)
    level.status = Level::STATUS_COMPLETED
    level.save
    @game[:status] = Level::STATUS_COMPLETED
    @game.save

    respond_to do |format|
      format.html { redirect_to @group, notice: 'Game switched to next level.'}
      format.json { render json: matingPlan }
    end
    

  end

  # POST /groups/1/nextlevel
  # POST /groups/1/nextlevel.json
  # Go to next level for all users in group
  def nextlevel
    @group = Group.find(params[:id])
    authorize! :create, @group 
    @group.mate()
    users_in_group = User.where(:group_id => @group[:id])

    #@group.users = []
    #users_in_group.each do |user|
    #    @group.users << { :id => user[:id], :email => user[:email] }
    #end

    @users = User.where(:group_id => @group[:id])

    @games = Game.where(:group_id => @group[:id])

    respond_to do |format|
      format.html { render :show }# show.html.erb
      format.json { render json: @group }
    end 
    
  end

  # POST /groups/1/generateusers/10
  # POST /groups/1/generateusers/10.json
  # Generate a umberof fake accounts
  def generateusers
    @group = Group.find(params[:id])
    authorize! :create, @group

    # Delete all users in group
    users_in_group = User.where(:group_id => @group[:id])
    users_in_group.each do |user|
        user.destroy
    end

    @quantity = params[:quantity]
    @users = Array.new
    Game.generate_new_cattle(@quantity,'group'+@group[:id].to_s,@group[:bulls],@group[:cows])
    uuid = UUID.new
    (1..@quantity.to_i).each do |n|
        user = User.new()
        user.fake = 1
        user.usertype = User::STUDENT
        user.password = SecureRandom.hex(16)
        user.password_confirmation =  user.password
        user.email = 'student-'+uuid.generate+'@fake.org'
        user.group_id = @group[:id]
        user.confirm!
        user.save(:validate => false)
        # Add a game to the user, associate one of the cattles to the user
        game = Game.new(:user_id => user.id, :cattle => n, :group_id => user.group_id, :level => 1, :status => Level::STATUS_NEW)
        game.load_statistics()
        game.save!
        # Create first level e.g. first generation
        level = Level.new(:game_id => game.id, :status => Level::STATUS_NEW, :level => 1)
        level.save!
        @users << user
    end

    respond_to do |format|
        UserMailer.users_created_email(@group, @users).deliver
        format.html 
        format.json { render json: {}.to_json }
    end
  end

  # GET /groups/1/market/open
  # GET /groups/1/market/open.json
  def open_market
    @group = Group.find(params[:id])
    authorize! :create, @group
    @group.market = Market::STATUS_OPEN
    @group.save!

    # Reset any previous market
    # Delete all markets in group
    markets_in_group = Market.delete_all("group_id = "+@group[:id].to_s)
    bids_in_group = Bid.delete_all("group_id = "+@group[:id].to_s)

    respond_to do |format|
        format.html { redirect_to @group, notice: 'Market is open.' }
        format.json { render json: {}.to_json }
    end

  end

  # GET /groups/1/market/bids
  # GET /groups/1/market/bids.json
  def bids_market
    @group = Group.find(params[:id])
    authorize! :create, @group
    @group.market = Market::STATUS_BIDS
    @group.save!
    respond_to do |format|
        format.html { redirect_to @group, notice: 'Bids are open.' }
        format.json { render json: {}.to_json }
    end

  end

  # GET /groups/1/market/close
  # GET /groups/1/marlet/close.json
  def close_market
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    @group.market = Market::STATUS_CLOSED
    @group.save!

    @group.close_market()

    respond_to do |format|
        format.html { redirect_to @group, notice: 'Market is closed.' }
        format.json { render json: {}.to_json }
    end

  end

  # GET /groups/1/market/cancel
  # GET /groups/1/marlet/cancel.json
  def cancel_market
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    @group.market = Market::STATUS_CLOSED
    @group.save!

    # Delete all markets in group
    markets_in_group = Market.delete_all("group_id = "+@group[:id].to_s)

    bids_in_group = Bid.delete_all("group_id = "+@group[:id].to_s)
    
    respond_to do |format|
        format.html { redirect_to @group, notice: 'Market is cancelled.' }
        format.json { render json: {}.to_json }
    end

  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row">
<div class="span6">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :levels %><br />
    <%= f.number_field :levels %>
  </div>

  <div class="field">
    <%= f.label :bulls %><br />
    <%= f.number_field :bulls %>
  </div>

  <div class="field">
    <%= f.label :cows %><br />
    <%= f.number_field :cows %>
  </div>

  <% if User.admin?(current_user) %>
  <div class="field">
    <% if User.admin?(current_user) %>
    <%= f.label :email %><br />
    <select name="group[email]">
    <%= @professors.each do |professor| %>
      <option value="<%= professor.email %>"><%= professor.email %></option>
    <% end %>
    </select>
    <% else %>
      <%= f.hidden_field :email %>
    <% end %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>
</div>

app/views/groups/_form_edit.html.erb
<div class="row">
<div class="span6">
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :levels %><br />
    <%= f.number_field :levels %>
  </div>

  <div class="field">
    <%= f.label :bulls %><br />
    <%= f.number_field :bulls %>
  </div>

  <div class="field">
    <%= f.label :cows %><br />
    <%= f.number_field :cows %>
  </div>


  <% if User.admin?(current_user) %>
  <div class="field">
    <% if User.admin?(current_user) %>
    <%= f.label :email %><br />
    <select name="group[email]">
    <%= @professors.each do |professor| %>
      <option value="<%= professor.email %>"><%= professor.email %></option>
    <% end %>
    </select>
    <% else %>
      <%= f.hidden_field :email %>
    <% end %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>
<div class="span6">
<% if User.professor?(current_user) && @group != nil  %>
  <%= form_for @group, :url => { :action => "generateusers" }, :method => "post" do |f| %>

  <div class="form-inputs">
    <%= label_tag(:quantity, "Generate students") %>
    <%= text_field_tag :quantity %>
  </div>

  <div class="form-actions">
    <%= submit_tag("Generate") %>
   <span>This will delete and replace existing students and cattles</span>
  </div>
  <% end %>
<% end %>

</div>
</div>

app/views/groups/edit.html.erb
<div class="offset1">
<h1>Editing group</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>
</div>

app/views/groups/generateusers.html.erb
<h2><%= @quantity %> accounts created</h2>

<table class="table table-bordered">
  <tr>
    <th>Login</th>
    <th>Password</th>
  </tr>

<% @users.each do |user| %>
  <tr class="info">
    <td><%= user.email %></td>
    <td><%= user.password %></td>
  </tr>
<% end %>
</table>

<a href="<%= group_path(@group) %>">Back to the group<a>

app/views/groups/index.html.erb
<h1>Listing groups</h1>
<%= form_for(:group, :html => { :class => "navbar-search"}, :method => "get") do |f| %>
  <%= f.text_field :search, :class => 'search-query' %>
  <%= f.submit 'Search', :class => 'btn'  %>
<% end %>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr class="info">
    <td><%= group.name %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group, :class => "btn" %></td>
    <td><%= link_to 'Edit', edit_group_path(group), :class => "btn" %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %></td>
  </tr>
<% end %>
</table>
<div class="digg_pagination">
    <div clas="page_info">
    </div>
    <%= will_paginate @groups, :container => false %>
  </div>
<br />

<%= link_to 'New Group', new_group_path, :class => "btn" %>

app/views/groups/new.html.erb
<div class="offset1">
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
<h2>  <%= @group.name %> </h2>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<p>
  <b>Professor:</b>
  <%= @group.email %>
</p>

<% if ! @group[:config_id].nil? %>
<p>
<a class="btn" href="<%= game_config_path(@group[:config_id]) %>">Configuration</a>
</p>
<% end %>

<h3>Students</h3>

<table class="table table-bordered">
  <tr>
    <th>Identifier</th><th>Nickname</th><th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr class="info">
    <td><%= user[:id]  %></td><td><%= user[:nickname]  %></td><td><a href="<%= user_path(user)  %>"><%= user[:email] %></a></td>
  </tr>
<% end %>
</table>

<h3>Game status</h3>
<table class="table table-bordered">
<thead><th>User id</th><th>Current level</th><th>Status</th><th></th></thead>
<tbody>
<% completed = true %>
<% @games.each do |game| %>
  <tr class="info">
  	<% if game[:status] != Level::STATUS_COMPLETED
  		completed = false
  	end %>
    <td><%= game[:user_id] %></td><td><%= game[:level] %></td><td><%= game[:status] %></td>
    <% if game[:status] == Level::STATUS_NEW || game[:status] == Level::STATUS_IN_PROGRESS %>
    <td><a class="btn" href="<%= game_path(game) %>">Show</a><a class="btn" href="<%= group_force_next_level_path(@group, game) %>">Force completion</a></td>
    <% else %>
    <td></td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>

<% if completed && @games.length>0%>
<div>
<h3>Generate next generation</h3>
	<a class="btn" href="<%= next_group_level_path(@group)  %>">Generate next generation</a>
</div>
<% end %>


<h3>Market Place</h3>
<div>
<% if @group.market == Market::STATUS_CLOSED %>
  <a class="btn" href="<%= group_open_market_path(@group)  %>">Open market</a>
<% else %>
  <a class="btn" href="<%= market_path(@group)  %>">Access market</a>
<% end %>
<% if @group.market == Market::STATUS_OPEN %>
  <a class="btn" href="<%= group_bids_market_path(@group)  %>">Open bids</a>
<% end %>
<% if @group.market == Market::STATUS_BIDS %>
  <a class="btn" href="<%= group_close_market_path(@group)  %>">Close bids</a>
<% end %>
  <a class="btn" href="<%= group_cancel_market_path(@group)  %>">Cancel market</a>
</div>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>