config/routes.rb
GameOfTheCalf::Application.routes.draw do

  devise_for :markets
  resources :markets
  as :market do
    post 'markets/:id/selection' => 'markets#selection'
    post 'markets/:id/vote' => 'markets#vote'
    get 'markets/:id/bids' => 'markets#bids', :as => 'bids_market'
  end

  devise_for :game_configs
  resources :game_configs

  devise_for :levels
  resources :levels

  devise_for :games
  resources :games
  as :game do
    post 'games/:id/nextlevel' => 'games#nextlevel', :as => 'next_level'
  end


  root :to => 'game#welcome'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :groups


  #devise_for :users
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :users

  devise_for :groups
  as :group do
    post 'groups/:id/generateusers' => 'groups#generateusers', :as => 'generate_users'
    get 'groups/:id/nextlevel' => 'groups#nextlevel', :as => 'next_group_level'
    get 'groups/:id/games/:gid/forcenextlevel' => 'groups#forcenextlevel', :as => 'group_force_next_level'
    get 'groups/:id/market/open' => 'groups#open_market', :as => 'group_open_market'
    get 'groups/:id/market/close' => 'groups#close_market', :as => 'group_close_market'
    get 'groups/:id/market/cancel' => 'groups#cancel_market', :as => 'group_cancel_market'
    get 'groups/:id/market/bids' => 'groups#bids_market', :as => 'group_bids_market'
  end

  match 'users/create' => 'users#create', :via => :post, :as => :create_user

  match 'game/locale/:id' => 'game#locale'

  match 'credits' => 'game#credits'

  match 'tutorial' => 'game#tutorial'

  match 'game/admin' => 'game#admin', :via => :get


end

app/models/user.rb
# Base class for all users
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :recent, order("created_at desc")

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :locale, :usertype, :group_id, :fake, :nickname
  # attr_accessible :title, :body

  belongs_to :group
  
  has_many :games, :dependent => :destroy

  # Checks if user is a site administrator.
  # Administrators are defined in Settings.
  def self.admin?(user)
    return false unless user
    Settings.admin.include?(user.email)
  end

  def self.professor?(user)
    if User.admin?(user) or user[:usertype] == PROFESSOR
      return true
    else
      return false
    end
  end

  # Administrator role
  ADMIN=0
  # Professor role, can create students and groups
  PROFESSOR=1
  # Student role, i.e. player
  STUDENT=2
end

app/controllers/users_controller.rb
# Base controller for managing users
class UsersController < ApplicationController

  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    if params[:user] && params[:user][:search]
      @users = User.paginate(:page => params[:page], :per_page => 20, :conditions => ['lower(email) LIKE ? ', "%#{params[:user][:search]}%"])
    else
      @users = User.paginate(:page => params[:page], :per_page => 20)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @groups = nil
    if @user.group_id != nil
        @groups = Group.where(:id => @user.group_id)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.usertype = User::STUDENT unless User.admin?(current_user)
    @user.password = SecureRandom.hex(16)
    @user.password_confirmation =  @user.password
    
    authorize! :create, @user
    
    @user.confirm!
    respond_to do |format|
      if @user.save(:validate => false)
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    
    authorize! :update, @user
    
    params[:user][:usertype] = User::STUDENT unless User.admin?(current_user)
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    
    authorize! :destroy, @user
    
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, :url => create_user_path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
     <%= f.input :nickname %>
    <% if User.admin?(current_user) %>
      <%= f.input :usertype, :collection => [ 0,1], label_method: lambda { |obj| t("usertype#{obj}") } %>
    <% else %>
      <%= f.hidden_field :usertype %>
    <% end %>
    <%= f.association :group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= simple_form_for(@user, :url => user_path(@user)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :nickname %>
    <% if User.admin?(current_user) %>
      <%= f.input :usertype, :collection => [ 0,1], label_method: lambda { |obj| t("usertype#{obj}") } %>
    <% else %>
      <%= f.hidden_field :usertype %>
    <% end %>
    <%= f.association :group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="offset1">
<h1>Editing user</h1>

<%= render 'form_edit' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= form_for(:user, :html => { :class => "navbar-search"}, :method => "get") do |f| %>
  <%= f.text_field :search, :class => 'search-query' %>
  <%= f.submit 'Search', :class => 'btn'  %>
<% end %>
<table class="table table-bordered">
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr class="info">
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user, :class => "btn" %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class => "btn" %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %></td>
  </tr>
<% end %>
</table>
<div class="digg_pagination">
    <div clas="page_info">
    </div>
    <%= will_paginate @users, :container => false %>
  </div>

<br />

<%= link_to 'New User', new_user_path, :class => "btn" %>

app/views/users/new.html.erb
<div class="offset1">
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="offset1">
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Nickname:</b>
  <%= @user.nickname %>
</p>


<% if @groups!=nil %>
<h2>Groups</h2>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
  </tr>

<% @groups.each do |group| %>
  <tr class="info">
    <td><a href="<%= group_path(group)  %>"><%= group.name %></a></td>
  </tr>
<% end %>
</table>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</div>