config/routes.rb
GameOfTheCalf::Application.routes.draw do

  devise_for :markets
  resources :markets
  as :market do
    post 'markets/:id/selection' => 'markets#selection'
    post 'markets/:id/vote' => 'markets#vote'
    get 'markets/:id/bids' => 'markets#bids', :as => 'bids_market'
  end

  devise_for :game_configs
  resources :game_configs

  devise_for :levels
  resources :levels

  devise_for :games
  resources :games
  as :game do
    post 'games/:id/nextlevel' => 'games#nextlevel', :as => 'next_level'
  end


  root :to => 'game#welcome'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :groups


  #devise_for :users
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources :users

  devise_for :groups
  as :group do
    post 'groups/:id/generateusers' => 'groups#generateusers', :as => 'generate_users'
    get 'groups/:id/nextlevel' => 'groups#nextlevel', :as => 'next_group_level'
    get 'groups/:id/games/:gid/forcenextlevel' => 'groups#forcenextlevel', :as => 'group_force_next_level'
    get 'groups/:id/market/open' => 'groups#open_market', :as => 'group_open_market'
    get 'groups/:id/market/close' => 'groups#close_market', :as => 'group_close_market'
    get 'groups/:id/market/cancel' => 'groups#cancel_market', :as => 'group_cancel_market'
    get 'groups/:id/market/bids' => 'groups#bids_market', :as => 'group_bids_market'
  end

  match 'users/create' => 'users#create', :via => :post, :as => :create_user

  match 'game/locale/:id' => 'game#locale'

  match 'credits' => 'game#credits'

  match 'tutorial' => 'game#tutorial'

  match 'game/admin' => 'game#admin', :via => :get


end

app/models/market.rb
class Market < ActiveRecord::Base
  attr_accessible :animal, :group_id, :owner, :status, :values

  has_many :bids, :dependent => :nullify

  # New level status
  STATUS_CLOSED = 0
  # open to proposals
  STATUS_OPEN = 1
  # bids in progress
  STATUS_BIDS = 2

  ANIMAL_PROPOSED = 0
  ANIMAL_SELECTED = 1


end

app/controllers/markets_controller.rb
require 'uri'

class MarketsController < InheritedResources::Base

  # POST /markets/1/vote
  # POST /markets/1/vote.json
  def vote
    @group = Group.find(params[:id])
    user = current_user
    game = Game.where(:group_id => params[:id], :user_id => user[:id]).first
    proposals = Market.where(:group_id => game[:group_id],
                             :owner => game[:cattle]).count()
    bids_opened = true
    if proposals==0
      flash[:alert] = "you did not propose bulls to the market, bids are not
accessible."
      redirect_to :action => "closed", :id => params[:id]
      bids_opened = false
    else
      # Reset bids
      Bid.delete_all("group_id = "+params[:id].to_s+" AND owner ="+user[:id].to_s)
      bids = JSON.parse(URI.unescape(params[:bids]))
      credit = 0
      bids.each do |bid|
          user_bid = Bid.new(market_id: bid["market"],
                            group_id: params[:id].to_i,
                            owner: user[:id], bid: bid["bid"].to_s)
          delta = bid["oldbid"] - bid["bid"]
          credit += delta
          if bid["bid"] > 0
              user_bid.save!
          end
      end
      game[:credit] += credit
      game.save!
      flash[:notice] = "Bids taken into account"
      redirect_to :action => "bids", :id => params[:id]
    end
  end

  # POST /markets/1/selection
  # POST /markets/1/selection.json
  def selection
    group = Group.find(params[:id])
    if group.market != Market::STATUS_OPEN
        redirect_to :action => "show", :id => params[:id]
        return
    end
    
    market = Market.new()
    market[:group_id] = params[:id]
    authorize! :create, market
    selection = JSON.parse(URI.unescape(params[:selection]))
    if selection.empty? or selection.length == 0
      flash[:alert] = "Selection empty"
      redirect_to :action => "show", :id => params[:id]
    else
      cattle = selection[0][0]
      Market.delete_all("group_id = "+params[:id].to_s+" AND owner = "+cattle.to_s)
      selection.each do |selected|
        market = Market.new(:group_id => params[:id], :owner => cattle.to_i,
                            :status => Market::ANIMAL_PROPOSED,
                            :animal => selected[1],
                            :values => JSON.dump(selected))
        market.save!
      end
      flash[:notice] = "Selection updated"
      redirect_to :action => "show", :id => params[:id]
    end

  end

  # GET /markets/1/bids
  # GET /markets/1/bids.json
  def bids
    @group = Group.find(params[:id])
    user = current_user
    @is_prof = false
    if User.admin?(user) or User.professor?(user)
      @is_prof = true
    end
    @credit = -1
    @game = nil
    @cattle = -1
    markets = Market.where(:group_id => params[:id])
    user_bids = nil
    if @is_prof
      user_bids = Bid.select("market_id, sum(bid) as bids").where(:group_id => params[:id]).group("market_id")
    else
      @game = Game.where(:group_id => params[:id], :user_id => user[:id]).first
      user_bids = Bid.select("market_id, sum(bid) as bids").where(:group_id => params[:id], :owner => user[:id]).group("market_id")
      @credit = @game.credit
      @cattle = @game[:cattle]
    end
    @animals = []
    markets.each do |market|
      if ! market[:values].nil? and ! market[:values].empty?
          animal = {}
          animal[:values] = JSON.parse(market[:values])
          animal[:bid] = 0
          animal[:oldbid] = 0
          animal[:market] = market[:id]
          user_bids.each do |user_bid|
              if user_bid[:market_id] == market[:id]
                  animal[:bid] = user_bid[:bids].to_i
                  animal[:oldbid] = animal[:bid]
                  break
              end
          end
          @animals << animal
      end
    end
    @animals = @animals.to_json
  end


  # GET /markets/1
  # GET /markets/1.json
  def show
    @group = Group.find(params[:id])
    user = current_user
    @selected = []
    @is_prof = false
    if User.admin?(user) or User.professor?(user)
      @is_prof = true
      markets = Market.where(:group_id => params[:id]) 
    else
      game = Game.where(:group_id => params[:id], :user_id => user[:id]).first
      game.credit = Settings.credit_default
      game.save!
      markets = Market.where(:group_id => params[:id], :owner => game[:cattle])
    end
    markets.each do |market|
      if ! market[:values].nil? and ! market[:values].empty?
          @selected << JSON.parse(market[:values])
      end
    end

    respond_to do |format|
      if @group.market == Market::STATUS_OPEN
        if User.admin?(user) or User.professor?(user)
            @bulls = []
        else
            game = Game.where(:group_id => params[:id], :user_id => user[:id]).first
            @bulls, cows = game.get_cattle(user, game[:level]) 
        end
        @max = Settings.market_max_user
        format.html { render :proposals }
      elsif @group.market == Market::STATUS_BIDS
        @max = Settings.market_max_final
        format.html { render :bids }
      else
        flash[:alert] = "Market is closed"
        format.html { render :closed }
      end
      format.json { render json: @markets }
    end
  end

end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= simple_form_for(@market) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :group %>
    <%= f.input :animal %>
    <%= f.input :owner %>
    <%= f.input :status %>
    <%= f.input :bids %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/markets/bids.html.erb
<div class="row">
<div class="span8">
<h2>Available bulls</h2>
<table id="bulls" class="table">
<thead><th>ID</th><th>P_W4M</th><th>P_W7M</th><th>g_W4Md</th><th>g_W7Md</th><th>g_W4Mm</th><th>g_W7Mm</th><th>bids</th><th></th></thead>
<tbody></tbody>
</table>
</div>
<div class="span4">
<% if ! @is_prof %>
<br/>
<%= form_tag(controller: "markets", action: "vote") do %>
<input type="hidden" id="game" name="game" value"<%= @game[:id] %>"/>
<input type="hidden" id="bids" name="bids" value="%5B%5D"/>
<button class="btn">Validate bids</button>
<% end %>
<a href="<%= game_path(@game) %>" class="btn">Back to game</a>
<% end %>
</div>
</div>
<% if ! @is_prof %>
<div>
<button class="btn btn-info">Credit: <span id="credit"> <%= @credit %></span> <i
class="icon-shopping-cart"></i></button>
</div>
<% end %>

<script>
var bulls = <%= @animals.to_s.html_safe %>;
var credit = <%= @credit.to_s %>;

$(function() {
$("#bids").val(encodeURIComponent(JSON.stringify(bulls)));
loadCattle('bulls',bulls);
$("table#bulls").tablesorter();

$(document).on("click",".vote", function() {
  var delta = parseInt($(this).attr("data-value"));
  if($(this).attr("data-type") == "minus") {
    delta = delta * -1;
  }
  setCredit($(this).attr("data-id"),delta);
  $("#bids").val(encodeURIComponent(JSON.stringify(bulls)));
});
});

function setCredit(animal, delta) {
    var testcredit = credit + (delta * -1);
    if(testcredit < 0 ) {
        return;
    }
    if(parseInt(bulls[animal]["bid"]) + delta < 0) {
        return;
    }
    credit += delta * -1;
    $("#credit").html(credit);
    bulls[animal]["bid"] = parseInt(bulls[animal]["bid"]) + delta;
    var id = bulls[animal]["values"][0]+"-"+bulls[animal]["values"][1];
    $("#bid"+id).html(bulls[animal]["bid"]);
}

function loadCattle(tablename, cattle) {
   table_data = $("table#"+tablename+" tbody");
   table_data.html("");
   for(var i=0;i<cattle.length;i++) {
        var data = '';
        // If not dead
        if(parseInt(cattle[i]["values"][13])==0) {
            mine = ""
            if(cattle[i]["values"][0]==<%= @cattle %>) {
              mine = " mine"
            }
            data += '<tr id="'+cattle[i]["values"][0]+'-'+cattle[i]["values"][1]+'" data-index="'+i+'" class="'+tablename+mine+'">';
            data += '<td>' + cattle[i]["values"][1] + '</td>';
            data += '<td>' + cattle[i]["values"][3] + '</td>';
            data += '<td>' + cattle[i]["values"][4] + '</td>';
            data += '<td>' + cattle[i]["values"][5] + '</td>';
            data += '<td>' + cattle[i]["values"][6] + '</td>';
            data += '<td>' + cattle[i]["values"][7] + '</td>';
            data += '<td>' + cattle[i]["values"][8] + '</td>';
            data += '<td id="bid'+cattle[i]["values"][0]+'-'+cattle[i]["values"][1]+'" class="bid">' + cattle[i]["bid"] + '</td>';
            <% if ! @is_prof %>
            data += '<td><button class="btn vote" data-value="100" data-type="plus" data-id="'+i+'">+100</button><button class="btn vote" data-value="100" data-type="minus" data-id="'+i+'">-100</button></td>';
            <% else %>
            data += '<td></td>';
            <% end %>
            data += '</tr>';
        }
        table_data.append(data);
    }
}
</script>

app/views/markets/closed.html.erb
<div class="row well">
<h1>Market is closed</h1>
</div>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<h1>Listing markets</h1>

<table>
  <tr>
    <th>Group</th>
    <th>Animal</th>
    <th>Owner</th>
    <th>Status</th>
    <th>Bids</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markets.each do |market| %>
  <tr>
    <td><%= market.group %></td>
    <td><%= market.animal %></td>
    <td><%= market.owner %></td>
    <td><%= market.status %></td>
    <td><%= market.bids %></td>
    <td><%= link_to 'Show', market %></td>
    <td><%= link_to 'Edit', edit_market_path(market) %></td>
    <td><%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Market', new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render 'form' %>

<%= link_to 'Back', markets_path %>

app/views/markets/proposals.html.erb
<div class="row">
<% if ! @is_prof %>
<div class="span6">
<h2>Available bulls</h2>
<table id="bulls" class="table">
<thead><th>ID</th><th>P_W4M</th><th>P_W7M</th><th>g_W4Md</th><th>g_W7Md</th><th>g_W4Mm</th><th>g_W7Mm</th><th>Mating</th></thead>
<tbody></tbody>
</table>
</div>
<% end %>
<div class="span6">
<h2>Selected bulls</h2>
<table id="selected" class="table">
<thead><th>ID</th><th>P_W4M</th><th>P_W7M</th><th>g_W4Md</th><th>g_W7Md</th><th>g_W4Mm</th><th>g_W7Mm</th></thead>
<tbody></tbody>
</table>
<% if ! @is_prof %>
<br/>
<%= form_tag(controller: "markets", action: "selection") do %>
<input type="hidden" id="selection" name="selection" value=""/>
<button class="btn">Validate transaction</button>
<% end %>
<% end %>
</div>
</div>


<script>
var bulls = <%= @bulls.to_s.html_safe %>;
var max = <%= @max.to_s %>;
var selected = <%= @selected.to_s.html_safe %>;

$(function() {
loadCattle('bulls',bulls);
$("table#bulls").tablesorter();
loadCattle('selected',selected);
$("table#selected").tablesorter();

$(document).on("click","table#bulls tr", function() {
  if(selected.length>=max) {
    alert("you already reached the maximum of proposal ("+max+")");
    return;
  }
  var animal = $(this).attr("data-id");
  var index = $(this).attr("data-index");
  var alreadyselected = false;
  for(var i=0;i<selected.length;i++) {
    if(selected[i][1] == animal) {
      alreadyselected = true;
      break;
    }
  }
  if(! alreadyselected) {
    selected.push(bulls[index]);
    $("#selection").val(encodeURIComponent(JSON.stringify(selected)));
    loadCattle('selected',selected);
  }

});

});

$(document).on("click","table#selected tr", function() {
  var index = -1;
  var animal = $(this).attr("data-id");
  for(var i=0;i<selected.length;i++) {
    if(selected[i][1] == animal) {
      index = i
      break;
    }
  }
  if(index>=0) {
    selected.splice(index,1);
    $("#selection").val(encodeURIComponent(JSON.stringify(selected)));
  }
  $(this).remove();
});


function loadCattle(tablename, cattle) {
   table_data = $("table#"+tablename+" tbody");
   table_data.html("");
   for(var i=0;i<cattle.length;i++) {
        var data = '';
        // If not dead
        if(parseInt(cattle[i][13])==0) {
            data += '<tr data-id="'+cattle[i][1]+'" data-index="'+i+'" class="'+tablename+'">';
            data += '<td>' + cattle[i][1] + '</td>';
            data += '<td>' + cattle[i][3] + '</td>';
            data += '<td>' + cattle[i][4] + '</td>';
            data += '<td>' + cattle[i][5] + '</td>';
            data += '<td>' + cattle[i][6] + '</td>';
            data += '<td>' + cattle[i][7] + '</td>';
            data += '<td>' + cattle[i][8] + '</td>';
            data += '</tr>';
        }
        table_data.append(data);
    }
}
</script>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @market.group %>
</p>

<p>
  <b>Animal:</b>
  <%= @market.animal %>
</p>

<p>
  <b>Owner:</b>
  <%= @market.owner %>
</p>

<p>
  <b>Status:</b>
  <%= @market.status %>
</p>

<p>
  <b>Bids:</b>
  <%= @market.bids %>
</p>


<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>